<?php

$title = 'Categorias';

$this->headTitle($title);

 ?>

 <h1><?=$this->escapeHtml($title)?></h1>  
<div class="col-md-12 text-right">
    <a class="btn btn-success" href="<?php echo $this->url('categoria',['action' => 'add']) ?>">Novo</a>
</div>
        
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($categorias as $categoria): ?>
      <tr>
        <td><?= $this->escapeHtml($categoria->getId()) ?></td>
        <td><?= $this->escapeHtml($categoria->getNome()) ?></td>
        <td><?= $this->escapeHtml($categoria->getDescricao()) ?></td>
        <td>
            <a class="btn btn-warning" href="<?php echo $this->url('categoria',array('action' => 'edit','id' => $categoria->getId())) ?>">Edit</a>
            <a class="btn btn-danger" href="<?php echo $this->url('categoria',['action' => 'delete','id' => $categoria->getId()]) ?>">Delete</a>
        </td>
      </tr>

    <?php endforeach ?>
    </tbody>
  </table>
