<?php

$title = 'Categorias';

$this->headTitle($title);

 ?>

 <h1><?=$this->escapeHtml($title)?></h1>  
<div class="col-md-12 text-right">
    <a class="btn btn-success" href="<?php echo $this->url('produto',['action' => 'add']) ?>">Novo</a>
</div>
        
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nome</th>
          <th>Valor</th>
          <th>Categoria</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($produtos as $produto): ?>
      <tr>
        <td><?= $this->escapeHtml($produto->getId()) ?></td>
        <td><?= $this->escapeHtml($produto->getNome()) ?></td>
          <td><?= $this->escapeHtml($produto->getValor()) ?></td>
          <td><?= $this->escapeHtml($produto->getNomeCategoria()) ?></td>
        <td>
            <a class="btn btn-warning" href="<?php echo $this->url('produto',array('action' => 'edit','id' => $produto->getId())) ?>">Edit</a>
            <a class="btn btn-danger" href="<?php echo $this->url('produto',['action' => 'delete','id' => $produto->getId()]) ?>">Delete</a>
        </td>
      </tr>

    <?php endforeach ?>
    </tbody>
  </table>
