<?php

$title = 'All Users';

$this->headTitle($title);

 ?>

 <h1><?=$this->escapeHtml($title)?></h1>  

        
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($users as $user): ?>
      
      <tr>
        <td><?= $this->escapeHtml($user->getId()) ?></td>
        <td><?= $this->escapeHtml($user->getName()) ?></td>
        <td><?= $this->escapeHtml($user->getEmail()) ?></td>
        <td>
            <a class="btn btn-warning" href="<?php echo $this->url('produto',['action' => 'edit','id' => $user->getId()]) ?>">Edit</a>
            <a class="btn btn-danger" href="<?php echo $this->url('produto',['action' => 'delete','id' => $user->getId()]) ?>">Delete</a>
        </td>
      </tr>

    <?php endforeach ?>
    </tbody>
  </table>
